// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbkfqoindbaszxigruph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxia2Zxb2luZGJhc3p4aWdydXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTU2NzcsImV4cCI6MjA3MjI5MTY3N30.AALFz0b2-9-2NuGyjJBEoe1u1VZ9JXLP-AJYiH1YY0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});